name: Drupal Alpine Dev

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - TAG_FROM: "php7.4-alpine"
            tag: "php7.4-alpine-dev"
          - TAG_FROM: "php8.1-alpine"
            tag: "php8.1-alpine-dev"
          - TAG_FROM: "php8.2-alpine"
            tag: "php8.2-alpine-dev"
          - TAG_FROM: "php8.3-alpine"
            tag: "php8.3-alpine-dev"
          - TAG_FROM: "10-php8.3-alpine"
            KEEP_DRUPAL_FILES: 1
            tag: "10-php8.3-alpine-dev"
          - TAG_FROM: "php8.4-alpine"
            tag: "php8.4-alpine-dev"
          - TAG_FROM: "11-php8.4-alpine"
            KEEP_DRUPAL_FILES: 1
            tag: "11-php8.4-alpine-dev"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:drupal"
          platforms: linux/amd64,linux/arm64
          file: "alpine.dev.Dockerfile"
          tags: lawxen/drupal:${{ matrix.version.tag }},registry.cn-hangzhou.aliyuncs.com/lawxen/drupal:${{ matrix.version.tag }}
          build-args: |
            TAG_FROM=${{ matrix.version.TAG_FROM }}